name: Build
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild .\PhysicsGame.sln /p:Configuration=Release

    - name: Create artifact directoy
      run: |
        mkdir ./artifact
        mkdir ./PhysicsGame

    - name: Copy files
      run: copy ./Build/PhysicsGame/Release/win32/PhysicsGame.exe ./artifact/Pinball_Physics_II-main

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Binary
        path: ./artifact/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: MyReleaseMessage

      - name: Download a Build artefact
        uses: actions/download-artifact@v4
        with:
          name: Windows-Binary
          path: ./artifact/
      - name: Display structure of downloaded files
        run: ls -R ./artifact/

      - name: Github Releases
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: Build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
